type: "project"
style: "dark"
title: "EELISA Project - ya2ro"
goal: "Develop a tool to which you pass basic information of a project or a research article (such as the datasets, software, people who have been involved, bibliograpy...) and generates two files with structured information with the intention of easing the readability for machines and people. One file is a webpage with all the relevant information and the other one is a Research Object."
social_motivation: "[INSERT MOTIVATION] Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis neque quam. Cras porttitor ipsum sit amet risus feugiat, ut cursus sapien suscipit. Sed vitae vehicula ante. Fusce luctus ornare risus, eget porta libero laoreet at. Etiam nec erat tellus. Duis convallis mauris erat, et pellentesque nunc ornare sed. Mauris feugiat lectus sit amet neque malesuada mollis. Aenean in felis posuere, aliquet odio sed, malesuada massa. Cras a sapien ac elit maximus condimentum eu et libero. Donec quis tincidunt mi. Praesent id odio at augue tincidunt hendrerit. Suspendisse neque mi, porta in efficitur eget, dictum vitae eros. Donec et erat non lorem lobortis pharetra. Maecenas euismod varius justo, sit amet elementum ipsum suscipit eu. Nunc bibendum nunc quis congue fermentum. Integer tincidunt sed enim nec elementum."
sketch: "images/sketch_ya2ro.jpg"
#involved_institutions: "(maybe can be automatically gathered from participants)"
areas: 
  - "Programming: Some description."
  - "Research: Some description."
  
demo: 
  -
    link: "https://oeg-upm.github.io/EELISA-research-object/output/index-en.html"
    description: "This is a description for a demo for the ya2ro EELISA project."
  -
    name: "GitHub Pages demo"
    link: "https://oeg-upm.github.io/EELISA-research-object/output/index-en.html"
    description: "This is a SECOND description for a demo for the ya2ro EELISA project but with name."

datasets: 
  doi_datasets: "www.link-doi.com"
  datasets_links:   
    - 
      link: "www.linkD1.com" 
      name: "name dataset 1"
      description: "description dataset 1"
      doi_dataset: "www.link-doi-1.com"
    - 
      link: "www.linkD2.com" 
      name: "name dataset 2"
      description: "description dataset 2"
      doi_dataset: "www.link-doi-2.com"

software: 
  - 
    link: "https://github.com/oeg-upm/EELISA-research-object" 
    #name: "EELISA-research-object"
    description: "Tool to which you pass basic information of a project or a research article (such as the datasets, software, people who have been involved, bibliograpy ...) and generates two files with structured information with the intention of easing the readability for machines and people. One file is a webpage with all the relevant information and the other one is a Research Object."
  #-
    #link: "https://github.com/KnowledgeCaptureAndDiscovery/somef/"
    #description: "A command line interface for automatically extracting relevant information from readme files."

bibliography: 
  - "Bibliography entry 1"
  - "Bibliography entry 2"
  - "Bibliography entry 3"

participants:  
  -
    orcid: "https://orcid.org/0000-0003-0454-7145"
    role: "Coordinator"
  -
    name: "Antonia Pavel"
    position: "Research Assistant at Universidad Politécnica de Madrid"
    description: "Student of the double major in Computer Engineering and Business Administration and Management from Universidad Politécnica de Madrid, Spain."
    web: "https://github.com/PavelAntonia"
    photo: "AntoniaPavel.jpg"


