 type: "project"
 title: "EELISA Project"
 goal: "EELISA Project: Develop a tool to which you pass basic information of a project or a research article (such as the datasets, software, people who have been involved, bibliograpy ...) and generates two files with structured information with the intention of easing the readability for machines and people. One file is a webpage with all the relevant information and the other one is a Research Object."
 social_motivation: "[INSERT MOTIVATION]"
 sketch: "imgages/Sketch.png"
 #involved_institutions: "(maybe can be automatically gathered from participants)"
 areas: 
   - "Programming"
   - "Research"
 demo: "https://oeg-upm.github.io/EELISA-research-object/output/index-en.html"
 datasets: 
   doi_datasets: "www.link-doi.com"
   datasets_links:   
      - 
         link: "www.linkD1.com" 
         name: "name dataset 1"
         description: "description dataset 1"
         doi_dataset: "www.link-doi-1.com"
      - 
         link: "www.linkD2.com" 
         name: "name dataset 2"
         description: "description dataset 2"
         doi_dataset: "www.link-doi-2.com"
  
 software: 
   - 
      link: "https://github.com/oeg-upm/EELISA-research-object" 
      name: "EELISA-research-object"
      description: "description software 1"
   - 
      link: "www.linkS2.com" 
      name: "name link 2"
      description: "Tool to which you pass basic information of a project or a research article (such as the datasets, software, people who have been involved, bibliograpy ...) and generates two files with structured information with the intention of easing the readability for machines and people. One file is a webpage with all the relevant information and the other one is a Research Object."

 bibliography: 
   - "Work in progress..."

 participants:  
   -
      orcid: "https://orcid.org/0000-0003-0454-7145"
      coordinator: "True"
   -    
      name: "Antonia Pavel"
      position: "Research Assistant at Universidad Politécnica de Madrid"
      description: "Student of the double major in Computer Engineering and Business Administration and Management from Universidad Politécnica de Madrid, Spain."
      web: "https://github.com/PavelAntonia"
      photo: "AntoniaPavel.jpg"


